version: "3.1"

services:
  postgres:
    build: ./srcs/postgres/.
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}


  backend:
    build: ./srcs/backend/.
    ports:
      - "3333:3333"
    volumes:
      - ./srcs/backend/backend:/backend
#
#  frontend:
#    build: ./srcs/frontend/.
#    ports:
#      - "3000:3000"
#    volumes:
#      -
